name : dotnet-blazor-crud

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build and push the docker image
      inputs:
        command: buildAndPush
        containerRegistry: dockerHub
        repository: thbst16/blazor-crud
        tags: |
          $(Build.BuildId)
          latest