name : dotnet-blazor-crud
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        command: build
        containerRegistry: dockerhub-connection
        repository: thbst16/blazor-crud
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push the image to Dockerhub
      inputs:
       command: push
       containerRegistry: dockerhub-connection
       repository: thbst16/blazor-crud
       tags: |
         $(Build.BuildId)
         latest

- stage: Deploy
  displayName: Deploy docker container
  dependsOn: Build
  jobs:

  - job: Deploy
    displayName: Deploy the container to Azure Web App using Docker Compose
    steps:
    - task: CmdLine@2
      inputs:
        script: dir
        workingDirectory: $(workingDirectory) 
    - task: AzureWebAppContainer@1
      displayName: Deploy the docker image
      inputs:
        azureSubscription: Subscription-1 (a96d1be0-8bbf-4b78-bf76-fe18462f59b8)
        appName: becksblazor
        multicontainerConfigFile: $(workingDirectory)/docker-compose.yml