# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build BlazorCrud.sln --configuration $(buildConfiguration)
    dotnet publish BlazorCrud.Client/BlazorCrud.Client.csproj --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    dotnet publish BlazorCrud.Server/BlazorCrud.Server.csproj --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'Building and Packaging BlazorCrud...'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Blazor BlazorCrud Build Artifacts'