version: 2
jobs:
  build:

    working_directory: ~/circleci-blazor-crud

    docker:
      - image: microsoft/dotnet:sdk

    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - checkout

      # Setup remote docker, necessary in Circle 2.0
      - setup_remote_docker
      
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # Restore NuGet packages
      - run: dotnet restore

      # Build and produce full / publish output
      - run: dotnet publish

      #Store output of build
      - store_artifacts:
          path: bin/Debug/netcoreapp2.0/publish/